## 第５章　演習２
## 問題１
### （１）下記のプログラムを実行してください。
### （２）予測・比較・学習部分の処理、それに伴う関数 vect_mat_mul の修正をそれぞれコメントに従って実装してください。

### 👇リスト

In [1]:
# NumPyのインポート、別名 np
import numpy as np

# 加重和（内積）を求める関数 w_sum の定義
def w_sum(a, b):
    # ２つの引数のリストの長さが等しいとき以下を実行する
    assert(len(a) == len(b))
    # 加重和の初期化
    output = 0
    # 加重和を求める
    # 引数のリストの長さ分繰り返す
    for i in range(len(a)):
        # リストの要素同士を掛けて合計を求める
        output += (a[i] * b[i])
    # 加重和を返す
    return output

# ベクトルと行列のかけ算を求める関数 vect_mat_mul の定義
def vect_mat_mul(vect, matrix):
    # ベクトルと行列の行リストの長さが等しいとき以下を実行する
    assert(len(vect) == len(matrix))
    # 加重和リストの初期化
    output = [0, 0, 0]
    # ベクトルの長さ（＝行列の行リストの長さ）分繰り返す
    for i in range(len(vect)):
        # ベクトルの行列の各行との加重和を求める
        output[i] = w_sum(vect, matrix[i])
    # 加重和のリストを返す
    return output



# ２つのリストの要素間を総なめして要素ごとのかけ算をして
# その結果を行列に格納する関数 outer_prod の定義
def outer_prod(a, b):
    # a 行 b 列のゼロ行列を生成する
    out = np.zeros((len(a), len(b)))
    # a 行 b 列の行列にリスト a とリスト b の
    # 要素を総なめしたかけ算を行い、行列に格納する
    for i in range(len(a)):
        for j in range(len(b)):
            out[i][j] = a[i] * b[j]
    # 要素間のかけ算の結果を保存した行列を返す
    return out

# 予測値を求める関数 nuural_network の定義
def neural_network(input, weights):
    # ベクトルと行列の加重和を求める
    pred = vect_mat_mul(input, weights)
    # 予測値のリストを返す
    return pred

# 重みの初期化
            #toes %win #fans
weights = [ [0.1, 0.1, -0.3], # けが？
            [0.1, 0.2, 0.0],  # 勝った？
            [0.0, 1.3, 0.1] ] # 悲しい？

# シーズン４試合の足指の数の平均
toes  = [8.5, 9.5, 9.9, 9.0]
# シーズン４試合の勝率
wlrec = [0.65,0.8, 0.8, 0.9]
# シーズン４試合のファンの数
nfans = [1.2, 1.3, 0.5, 1.0]

# シーズン４試合のけが度
hurt  = [0.1, 0.0, 0.0, 0.1]
# シーズン４試合の勝ち負け
win   = [  1,   1,   0,   1]
# シーズン４試合の悲しみ度
sad   = [0.1, 0.0, 0.1, 0.2]
# アルファの初期化
alpha = 0.01
# 入力データの設定（シーズン第１試合の [足指の数の平均値, 勝率, ファンの数]
input = [toes[0], wlrec[0], nfans[0]]
# シーズン第１試合の結果の設定（[けが度, 勝ち負け, 悲しみ度]
true  = [hurt[0], win[0], sad[0]]

# 勾配降下法による学習

# 予測値を求める
pred = neural_network(input,weights)

# 誤差の初期化
error = [0, 0, 0]
# デルタの初期化
delta = [0, 0, 0]

# 予測値の数分繰り返す
for i in range(len(true)):
    # 誤差を求める
    error[i] = (pred[i] - true[i]) ** 2
    # デルタを求める
    delta[i] = pred[i] - true[i]

# 重みの微調整量を求め行列に格納する
weight_deltas = outer_prod(delta, input)

# 重み行列を更新する
for i in range(len(weights)):
    for j in range(len(weights[0])):
        weights[i][j] -= alpha * weight_deltas[i][j]

# 更新された重み行列を表示する
for i in range(len(weights)):
    print('{} {} {}'.format(weights[i][0], weights[i][1], weights[i][2]))

0.061325 0.0970425 -0.30546
0.1017 0.20013 0.00023999999999999887
-0.07352500000000001 1.2943775 0.08962


### 👇未完成リスト

In [2]:
# NumPyのインポート、別名 np
import numpy as np

# 加重和（内積）を求める関数 w_sum の定義
def w_sum(a, b):
    # ２つの引数のリストの長さが等しいとき以下を実行する
    assert(len(a) == len(b))
    # 加重和の初期化
    output = 0
    # 加重和を求める
    # 引数のリストの長さ分繰り返す
    for i in range(len(a)):
        # リストの要素同士を掛けて合計を求める
        output += (a[i] * b[i])
    # 加重和を返す
    return output

# ベクトルと行列のかけ算を求める関数 vect_mat_mul の定義

    # ベクトルと行列の行リストの長さが等しいとき以下を実行する
    
    # 加重和リストの初期化
    
    # ベクトルの長さ（＝行列の行リストの長さ）分繰り返す
    
        # ベクトルの行列の各行との加重和を求めて out に追加する
        
    # 加重和のリストを返す
    

# ２つのリストの要素間を総なめして要素ごとのかけ算をして
# その結果を行列に格納する関数 outer_prod の定義
def outer_prod(a, b):
    # a 行 b 列のゼロ行列を生成する
    out = np.zeros((len(a), len(b)))
    # a 行 b 列の行列にリスト a とリスト b の
    # 要素を総なめしたかけ算を行い、行列に格納する
    for i in range(len(a)):
        for j in range(len(b)):
            out[i][j] = a[i] * b[j]
    # 要素間のかけ算の結果を保存した行列を返す
    return out

# 予測値を求める関数 nuural_network の定義
def neural_network(input, weights):
    # ベクトルと行列の加重和を求める
    pred = vect_mat_mul(input, weights)
    # 予測値のリストを返す
    return pred

# 学習関数 grad_descent_learn(input, truth, pred, weights, alpha) の定義
'''
関数名：grad_descent_learn
引数：
    input：入力値リスト
    truth：目的値リスト
    pred：予測値リスト
    weights：重みリスト
    alpha：重み再微調整値
処理：勾配降下法に基づき重みを修正する
戻り値：修正された重みリスト
'''

    # デルタの初期化
    
    # 予測値の数分繰り返す
    
        # デルタを求めてデルタのリストに追加する
        
    # 重みの微調整量を求め行列に格納する
    
    # 重み行列を更新する（２重ループ）
    
    

    # 重み行列を返す
    


# 重みの初期化
            #toes %win #fans
weights = [ [0.1, 0.1, -0.3], # けが？
            [0.1, 0.2, 0.0],  # 勝った？
            [0.0, 1.3, 0.1] ] # 悲しい？

# シーズン４試合の足指の数の平均
toes  = [8.5, 9.5, 9.9, 9.0]
# シーズン４試合の勝率
wlrec = [0.65,0.8, 0.8, 0.9]
# シーズン４試合のファンの数
nfans = [1.2, 1.3, 0.5, 1.0]

# シーズン４試合のけが度
hurt  = [0.1, 0.0, 0.0, 0.1]
# シーズン４試合の勝ち負け
win   = [  1,   1,   0,   1]
# シーズン４試合の悲しみ度
sad   = [0.1, 0.0, 0.1, 0.2]
# アルファの初期化
alpha = 0.01
# 入力データの設定（シーズン第１試合の [足指の数の平均値, 勝率, ファンの数]
input = [toes[0], wlrec[0], nfans[0]]
# シーズン第１試合の結果の設定（[けが度, 勝ち負け, 悲しみ度]
truth  = [hurt[0], win[0], sad[0]]

# 勾配降下法による学習
# 予測値を求める

# 学習する


# 予測値を表示

print('更新された重み')
# 更新された重み行列を表示する（ループ）




予測値 = [0.555, 0.9800000000000001, 0.9650000000000001]
更新された重み
0.06132500 : 0.09704250 : -0.30546000
0.10170000 : 0.20013000 : 0.00024000
-0.07352500 : 1.29437750 : 0.08962000


## 問題２
### ▶ 問題１のプログラムにおいて、学習を１０回実施するプログラムを下記の未完成リストのコメントに従って実装してください。

### 👇未完成リスト

In [3]:
# NumPyのインポート、別名 np
import numpy as np

# 加重和（内積）を求める関数 w_sum の定義
def w_sum(a, b):
    # ２つの引数のリストの長さが等しいとき以下を実行する
    assert(len(a) == len(b))
    # 加重和の初期化
    output = 0
    # 加重和を求める
    # 引数のリストの長さ分繰り返す
    for i in range(len(a)):
        # リストの要素同士を掛けて合計を求める
        output += (a[i] * b[i])
    # 加重和を返す
    return output

# ベクトルと行列のかけ算を求める関数 vect_mat_mul の定義

    # ベクトルと行列の行リストの長さが等しいとき以下を実行する
    
    # 加重和リストの初期化
    
    # ベクトルの長さ（＝行列の行リストの長さ）分繰り返す
    
        # ベクトルの行列の各行との加重和を求める
        
    # 加重和のリストを返す
    

# ２つのリストの要素間を総なめして要素ごとのかけ算をして
# その結果を行列に格納する関数 outer_prod の定義
def outer_prod(a, b):
    # a 行 b 列のゼロ行列を生成する
    out = np.zeros((len(a), len(b)))
    # a 行 b 列の行列にリスト a とリスト b の
    # 要素を総なめしたかけ算を行い、行列に格納する
    for i in range(len(a)):
        for j in range(len(b)):
            out[i][j] = a[i] * b[j]
    # 要素間のかけ算の結果を保存した行列を返す
    return out

# 予測値を求める関数 nuural_network の定義
def neural_network(input, weights):
    # ベクトルと行列の加重和を求める
    pred = vect_mat_mul(input, weights)
    # 予測値のリストを返す
    return pred

# 学習関数 grad_descent_learn(input, truth, pred, weights, alpha) の定義
'''
関数名：grad_descent_learn
引数：
    input：入力値リスト
    truth：目的値リスト
    pred：予測値リスト
    weights：重みリスト
    alpha：重み再微調整値
処理：勾配降下法に基づき重みを修正する
戻り値：修正された重みリスト
'''

    # デルタの初期化
    
    # 予測値の数分繰り返す
    
        # デルタを求める
        
    # 重みの微調整量を求め行列に格納する
    
    # 重み行列を更新する（２重ループ）
    
    

    # 重み行列を返す
    

# 予測値と更新された重みを表示する関数 disp_lear の定義
'''
関数名：disp_learn
引数：
    pred = 予測値リスト
    weights = 重み行列
処理：予測値と重みを表示する。ただし、重みは小数点８桁
戻り値：なし
'''

    # 予測値を表示
    
    
    # 更新された重み行列を表示する（ループ）
    



# 重みの初期化
            #toes %win #fans
weights = [ [0.1, 0.1, -0.3], # けが？
            [0.1, 0.2, 0.0],  # 勝った？
            [0.0, 1.3, 0.1] ] # 悲しい？

# シーズン４試合の足指の数の平均
toes  = [8.5, 9.5, 9.9, 9.0]
# シーズン４試合の勝率
wlrec = [0.65,0.8, 0.8, 0.9]
# シーズン４試合のファンの数
nfans = [1.2, 1.3, 0.5, 1.0]

# シーズン４試合のけが度
hurt  = [0.1, 0.0, 0.0, 0.1]
# シーズン４試合の勝ち負け
win   = [  1,   1,   0,   1]
# シーズン４試合の悲しみ度
sad   = [0.1, 0.0, 0.1, 0.2]
# アルファの初期化
alpha = 0.01
# 入力データの設定（シーズン第１試合の [足指の数の平均値, 勝率, ファンの数]
input = [toes[0], wlrec[0], nfans[0]]
# シーズン第１試合の結果の設定（[けが度, 勝ち負け, 悲しみ度]
truth  = [hurt[0], win[0], sad[0]]

# 勾配降下法による学習（１０回）

    # 学習回数を表示
    
    # 予測値を求める
    
    # 学習する
    
    # 予測値と更新された重みを表示
    
    print()

学習 1 回目
予測値 = [0.555, 0.9800000000000001, 0.9650000000000001]
重み行列 = 
0.061325 : 0.0970425 : -0.30546
0.1017 : 0.20013 : 0.00023999999999999887
-0.07352500000000001 : 1.2943775 : 0.08962

学習 2 回目
予測値 = [0.217788125, 0.9948224999999999, 0.32392687499999984]
重み行列 = 
0.051313009374999996 : 0.0962768771875 : -0.3068734575
0.1021400875 : 0.20016365375 : 0.0003021299999999995
-0.092558784375 : 1.2929219753124999 : 0.0869328775

学習 3 回目
予測値 = [0.13049240085937502, 0.9986596746875, 0.15796906976562497]
重み行列 = 
0.04872115530195312 : 0.09607867658191406 : -0.3072393663103125
0.1022540151515625 : 0.20017236586453124 : 0.00031821390374999885
-0.09748615530507812 : 1.2925451763590232 : 0.0862372486628125

学習 4 回目
予測値 = [0.10789372027247063, 0.9996530232847265, 0.11500674293557611]
重み行列 = 
0.04805018907879312 : 0.096027367400143 : -0.30733409095358216
0.10228350817236075 : 0.20017462121318053 : 0.0003223776243332809
-0.09876172845460209 : 1.2924476325299419 : 0.0860571677475856

学習 5 回目
予測値 = [0.102

## 問題３
### ▶ 下図のネットワークにおいて、下記の実行結果のように１０回学習させるようにプログラムを実装してください
### 注意）実行結果と全く同じでなくても構いません。学習が目的値に向かって進むのであればOKです。
![](chap5_ex_2_3.png)

In [16]:
%config IPCompleter.greedy=True
# NumPyのインポート、別名 np
import numpy as np

# 加重和（内積）を求める関数 w_sum の定義




# ベクトルと行列のかけ算を求める関数 vect_mat_mul の定義




# ２つのリストの要素間を総なめして要素ごとのかけ算をして
# その結果を行列に格納する関数 outer_prod の定義





# 予測値を求める関数 nuural_network の定義




# 学習関数 grad_descent_learn(input, truth, pred, weights, alpha) の定義
'''
関数名：grad_descent_learn
引数：
    input：入力値リスト
    truth：目的値リスト
    pred：予測値リスト
    weights：重みリスト
    alpha：重み再微調整値
処理：勾配降下法に基づき重みを修正する
戻り値：修正された重みリスト
'''





# 予測値と更新された重みを表示する関数 disp_lear の定義
'''
関数名：disp_learn
引数：
    pred = 予測値リスト
    weights = 重み行列
処理：予測値と重みを表示する。ただし、重みは小数点８桁
戻り値：なし
'''




# 入力値 [身長、体重、年収、血液型] の初期化
inp=np.array([0.178,0.658,0.85,0.3])

# 重み行列の初期化
wei=np.array([[0.78,0.64,0.55,0.45],
             [0.62,0.42,0.38,0.71],
             [0.79,0.57,0.83,0.73]])



# 目的値の初期化
goal=np.array([1.0,1.0,1.0])

# alpha の初期化
alp=0.1

# １０回学習する
for i in range(10):
    pred=np.dot(wei,inp)
    err=pred-goal
    DaM=np.outer(inp,err).T
    wei-=(DaM*alp)
    print("学習",i+1,"回目\n予測値",pred)
    print("重み行列＝",wei)
'''
なぜか手本が、重みの表示が12個必要なのに9つしか表自されていない
考えられる限り、配列のインデックス同士を使っているので飛び出たインデックス分まで届かず
正方行列とみなされ、4×3(入力値、誤差)の外積和から重みを調節しているのでなく、3×3の形で内積してそのままの値を使って調整しまっている？
'''


学習 1 回目
予測値 [1.16246 0.92272 1.44018]
重み行列＝ [[0.77710821 0.62931013 0.5361909  0.4451262 ]
 [0.62137558 0.42508502 0.3865688  0.7123184 ]
 [0.7821648  0.54103616 0.7925847  0.7167946 ]]
学習 2 回目
予測値 [1.14171145 0.9325898  1.3839625 ]
重み行列＝ [[0.77458575 0.61998552 0.52414543 0.44087486]
 [0.62257549 0.42952062 0.39229867 0.71434071]
 [0.77533026 0.51577142 0.75994789 0.70527573]]
学習 3 回目
予測値 [1.1236128  0.94119908 1.33492481]
重み行列＝ [[0.77238544 0.6118518  0.51363834 0.43716647]
 [0.62362214 0.43338972 0.39729675 0.71610473]
 [0.7693686  0.49373337 0.73147928 0.69522798]]
学習 4 回目
予測値 [1.10782562 0.94870883 1.29214995]
重み行列＝ [[0.77046614 0.60475687 0.50447316 0.4339317 ]
 [0.62453512 0.43676467 0.40165649 0.71764347]
 [0.76416833 0.4745099  0.70664653 0.68646348]]
学習 5 回目
予測値 [1.09405469 0.95525947 1.25483808]
重み行列＝ [[0.76879197 0.59856807 0.49647851 0.43111006]
 [0.62533151 0.4397086  0.40545944 0.71898568]
 [0.75963222 0.45774156 0.6849853  0.67881834]]
学習 6 回目
予測値 [1.08204252 0.9609735 