In [16]:
import numpy as np
# 重み
wei=np.array([[0.1,0.1,-0.3],[0.1,0.2,0.0],[0.0,1.3,0.1]]).T
# 入力値
toes=np.array([8.5,9.5,9.9,9.0])
wlrec=np.array([0.65,0.8,0.8,0.9])
nfans=np.array([1.2,1.3,0.5,1.0])
inp=np.array([toes,wlrec,nfans]).T
# 目標値
hurt=np.array([0.1,0.0,0.0,0.1])
sad=np.array([0.1,0.0,0.1,0.2])
winR=np.array([1,1,0,1])
goal=np.array([hurt,winR,sad]).T
# 学習速度
alp=0.001
# 実行部
for j in range(100):
    for i in range(4):
        pred=np.dot(inp[i],wei)
        lis=goal[i]
        err=pred-lis
        DaM=err*inp[i]
        print(j+1,"週目",i+1,"回目　予測値",pred,"実際の結果",lis,"誤差",err,"各重み",wei)
        wei-=(DaM*alp)
print("重み",wei)

1 週目 1 回目　予測値 [0.555 0.98  0.965] 実際の結果 [0.1 1.  0.1] 誤差 [ 0.455 -0.02   0.865] 各重み [[ 0.1  0.1  0. ]
 [ 0.1  0.2  1.3]
 [-0.3  0.   0.1]]
1 週目 2 回目　予測値 [0.595137  1.1101508 1.1579592] 実際の結果 [0. 1. 0.] 誤差 [0.595137  0.1101508 1.1579592] 各重み [[ 9.613250e-02  1.000130e-01 -1.038000e-03]
 [ 9.613250e-02  2.000130e-01  1.298962e+00]
 [-3.038675e-01  1.300000e-05  9.896200e-02]]
1 週目 3 回目　予測値 [0.81336142 1.14915865 1.06151451] 実際の結果 [0.  0.  0.1] 誤差 [0.81336142 1.14915865 0.96151451] 各重み [[ 9.04786985e-02  9.99248794e-02 -2.54334696e-03]
 [ 9.04786985e-02  1.99924879e-01  1.29745665e+00]
 [-3.09521302e-01 -7.51206400e-05  9.74566530e-02]]
1 週目 4 回目　予測値 [0.49844798 1.06916052 1.23703726] 実際の結果 [0.1 1.  0.2] 誤差 [0.39844798 0.06916052 1.03703726] 各重み [[ 8.24264204e-02  9.90055524e-02 -3.02410422e-03]
 [ 8.24264204e-02  1.99005552e-01  1.29697590e+00]
 [-3.17573580e-01 -9.94447559e-04  9.69758958e-02]]
2 週目 1 回目　予測値 [0.33599802 0.96906324 0.92296719] 実際の結果 [0.1 1.  0.1] 誤差 [ 0.23599802 -0.03093

46 週目 2 回目　予測値 [-0.04584076  0.82913322  0.2301261 ] 実際の結果 [0. 1. 0.] 誤差 [-0.04584076 -0.17086678  0.2301261 ] 各重み [[ 0.0408758   0.07578735 -0.08102361]
 [ 0.0408758   0.17578735  1.21897639]
 [-0.3591242  -0.02421265  0.01897639]]
46 週目 3 回目　予測値 [0.26268638 0.88034925 0.1791849 ] 実際の結果 [0.  0.  0.1] 誤差 [0.26268638 0.88034925 0.0791849 ] 各重み [[ 0.04131128  0.07592404 -0.08132278]
 [ 0.04131128  0.17592404  1.21867722]
 [-0.35868872 -0.02407596  0.01867722]]
46 週目 4 回目　予測値 [0.02194651 0.80989539 0.38315018] 実際の結果 [0.1 1.  0.2] 誤差 [-0.07805349 -0.19010461  0.18315018] 各重み [[ 0.03871069  0.07521976 -0.08136237]
 [ 0.03871069  0.17521976  1.21863763]
 [-0.36128931 -0.02478024  0.01863763]]
47 週目 1 回目　予測値 [-0.07207369  0.72529535  0.12100388] 実際の結果 [0.1 1.  0.1] 誤差 [-0.17207369 -0.27470465  0.02100388] 各重み [[ 0.03941317  0.07539086 -0.08154552]
 [ 0.03941317  0.17539086  1.21845448]
 [-0.36058683 -0.02460914  0.01845448]]
47 週目 2 回目　予測値 [-0.04584076  0.82660519  0.22377961] 実際の結果 [0. 1. 0.

89 週目 1 回目　予測値 [-0.07207369  0.67614522  0.01406011] 実際の結果 [0.1 1.  0.1] 誤差 [-0.17207369 -0.32385478 -0.08593989] 各重み [[ 0.03941317  0.07064205 -0.09187825]
 [ 0.03941317  0.17064205  1.20812175]
 [-0.36058683 -0.02935795  0.00812175]]
89 週目 2 回目　予測値 [-0.04584076  0.77188965  0.10540858] 実際の結果 [0. 1. 0.] 誤差 [-0.04584076 -0.22811035  0.10540858] 各重み [[ 0.0408758   0.07085256 -0.09177512]
 [ 0.0408758   0.17085256  1.20822488]
 [-0.3591242  -0.02914744  0.00822488]]
89 週目 3 回目　予測値 [0.26268637 0.8255925  0.06058388] 実際の結果 [0.  0.  0.1] 誤差 [ 0.26268637  0.8255925  -0.03941612] 各重み [[ 0.04131128  0.07103504 -0.09191215]
 [ 0.04131128  0.17103504  1.20808785]
 [-0.35868872 -0.02896496  0.00808785]]
89 週目 4 回目　予測値 [0.0219465  0.75708282 0.26837234] 実際の結果 [0.1 1.  0.2] 誤差 [-0.0780535  -0.24291718  0.06837234] 各重み [[ 0.03871069  0.07037457 -0.09189245]
 [ 0.03871069  0.17037457  1.20810755]
 [-0.36128931 -0.02962543  0.00810755]]
90 週目 1 回目　予測値 [-0.07207369  0.67563958  0.01320553] 実際の結果 [0.1 1