## 第３章　実習問題２
## 問題１
### ▶ 下記のニューラルネットワークを実装するプログラムを作成してください。実行結果は下記のようになります。
#### ◎実装するニューラルネットワーク
![](chap3_ex_2.png)
#### ◎実行結果
![](chap3_ex_2_result.png)

In [3]:
# Numpyをインポート、別名を np とする
import numpy as np

def neural_network(input, weights):
    pred=0
    for i in range(len(input)):
        pred+=(input[i]*weights[i])
    return pred
'''
空のニューラルネットワーク neural_network の定義
関数名：neural_network
引数：input -> 入力、weights -> 重み
処理：入力と重みを掛けて返す
戻り値：入力と重みの乗算値
'''




# 重みの初期化

wei=[0.07,0.068,0.085,0.4]
# 入力値の初期化


# 予測する
res=neural_network([178.8,65.8,850,3], wei)

# 予測を出力
print("予測値",res,"%")

90.4404


## 問題２
### ▶ 下記のニューラルネットワークを実装するプログラムを作成してください。実行結果は下記のようになります。
#### ◎実装するニューラルネットワーク
![](chap3_ex_3.png)
#### ◎実行結果
![](chap3_ex_3_result.png)

In [9]:
# numpy をインポート
import numpy as np
def ele_mul(number,vector):
    return np.dot(vector,number)
'''
数値リスト（ベクトル）の各要素に
定数を掛けたリストを返す関数 ele_mul の定義
関数名：ele_mul
引数：number -> 定数、vector -> 数値リスト（ベクトル）
処理：vector の各要素に number を掛ける
戻り値：vector の各要素に number を掛けたリスト
'''




def neural_network(input, weights):
    return ele_mul(input,weights)

'''
空のニューラルネットワーク neural_network の定義
関数名：neural_network
引数：input -> 入力、weights -> 重み
処理：入力と重みの加重和を求める
戻り値：入力と重みの加重和
'''






# 重みの初期化
wei=np.array([0.67,0.88,0.45])

# 入力値の初期化

inp=90.4
# 予測する
pred=neural_network(inp, wei)

# 予測を出力

for i in pred:
    print(round(i,4),"%",end="")

60.568 %79.552 %40.68 %

## 問題３
### ▶ 下記のニューラルネットワークを実装するプログラムを作成してください。実行結果は下記のようになります。
#### ◎実装するニューラルネットワーク
![](chap3_ex_4.png)
#### ◎実行結果
![](chap3_ex_4_result.png)

In [13]:
import numpy as np
# 重み行列の初期化
          # 身長、体重、年収、血液型
                                         # イケメン?
                                         # 良いやつ?
                                         # できる男?
wei=np.array([[0.078,0.064,0.055,0.045],[0.063,0.042,0.038,0.071],[0.079,0.057,0.083,0.073]])

# ２つのベクトル（数値リスト）の内積を求める関数 w_sum の定義

    




# ベクトル（数値リスト）と行列の加重和を求める関数 vect_mat_mul の定義






# ニューラルネットワーク neural_network の定義




# 入力値 [身長、体重、年収、血液型] の初期化
# 身長 = 178.8、体重 = 65.8、年収 = 850、血液型 = 3
inf=np.array([178.8,65.8,850,3])

# 予測値を求める

pred=np.dot(wei,inf)
# 予測値を表示する
print(pred)

[65.0426 46.541  88.6448]


## 問題４
### ▶ テキストP２７におけるベクトル計算の各関数を定義して下記の実行結果となるようにプログラムを作成してください
#### ◎実行結果
![](chap3_ex_5_result.png)

In [18]:
import numpy as np
# 関数 elementwise_multiplication の定義

def elementwise_multiplication(a,b):
    return a*b


# 関数 elementwise_addition の定義

def elementwise_addition(a,b):
    return a+b



# 関数 vector_sum の定義

def vector_sum(a):
    return sum(a)



# 関数 vector_average の定義

def vector_average(a):
    return sum(a)/len(a)



# vec_a と vec_b の初期化
vec_a = [10, 20, 30, 40, 50]
vec_b = [5, 4, 3, 2, 1]
vec_a =np.array(vec_a)
vec_b =np.array(vec_b)

print('vec_a = ', vec_a)
print('vec_b = ', vec_b)

# ベクトルのかけ算
print(elementwise_multiplication(vec_a,vec_b))
# ベクトルのたし算
print(elementwise_addition(vec_a,vec_b))
# ベクトルの合計
print(vector_sum(vec_a))
# ベクトルの平均
print(vector_average(vec_a))

vec_a =  [10 20 30 40 50]
vec_b =  [5 4 3 2 1]
[50 80 90 80 50]
[15 24 33 42 51]
150
30.0
