In [2]:
# 全て学習
import numpy as np
wei=np.array([0.3,0.2,0.9])
wlrec=np.array([0.65,1.0,1.0,0.9])
hurt=np.array([0.1,0.0,0.0,0.1])
sad=np.array([0.1,0.0,0.1,0.2])
winR=np.array([1,1,0,1])
alp=0.01
goal=np.array([hurt,winR,sad])
# print(goal)
for i in range(4):
    pred=wlrec[i]*wei
    Tlis=goal.T[i]
    err=pred-Tlis
    DaM=err*wlrec[i]
    print(i+1,"回目　予測値",pred,"実際の結果",Tlis,"誤差",err,"各重み",wei)
    wei-=(DaM*alp)
print(wei)

[[0.1 0.  0.  0.1]
 [1.  1.  0.  1. ]
 [0.1 0.  0.1 0.2]]
1 回目　予測値 [0.195 0.13  0.585] 実際の結果 [0.1 1.  0.1] 誤差 [ 0.095 -0.87   0.485] 各重み [0.3 0.2 0.9]
2 回目　予測値 [0.2993825 0.205655  0.8968475] 実際の結果 [0. 1. 0.] 誤差 [ 0.2993825 -0.794345   0.8968475] 各重み [0.2993825 0.205655  0.8968475]
3 回目　予測値 [0.29638867 0.21359845 0.88787903] 実際の結果 [0.  0.  0.1] 誤差 [0.29638867 0.21359845 0.78787903] 各重み [0.29638867 0.21359845 0.88787903]
4 回目　予測値 [0.26408231 0.19031622 0.79200021] 実際の結果 [0.1 1.  0.2] 誤差 [ 0.16408231 -0.80968378  0.59200021] 各重み [0.29342479 0.21146247 0.88000023]
[0.29194805 0.21874962 0.87467223]


In [3]:
# 一回ずつ学習（重みを引き継がない）
import numpy as np
wei=np.array([0.3,0.2,0.9])
wlrec=np.array([0.65,1.0,1.0,0.9])
hurt=np.array([0.1,0.0,0.0,0.1])
sad=np.array([0.1,0.0,0.1,0.2])
winR=np.array([1,1,0,1])
alp=0.01
goal=np.array([hurt,winR,sad])
# print(goal)
for i in range(4):
    pred=wlrec[i]*wei
    Tlis=goal.T[i]
    err=pred-Tlis
    DaM=err*wlrec[i]
    wei-=(DaM*alp)
    print(i+1,"回目　予測値",pred,"実際の結果",Tlis,"誤差",err,"各重み",wei)


1 回目　予測値 [0.195 0.13  0.585] 実際の結果 [0.1 1.  0.1] 誤差 [ 0.095 -0.87   0.485] 各重み [0.2993825 0.205655  0.8968475]
2 回目　予測値 [0.2993825 0.205655  0.8968475] 実際の結果 [0. 1. 0.] 誤差 [ 0.2993825 -0.794345   0.8968475] 各重み [0.29638867 0.21359845 0.88787903]
3 回目　予測値 [0.29638867 0.21359845 0.88787903] 実際の結果 [0.  0.  0.1] 誤差 [0.29638867 0.21359845 0.78787903] 各重み [0.29342479 0.21146247 0.88000023]
4 回目　予測値 [0.26408231 0.19031622 0.79200021] 実際の結果 [0.1 1.  0.2] 誤差 [ 0.16408231 -0.80968378  0.59200021] 各重み [0.29194805 0.21874962 0.87467223]
